services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: task_manager_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      POSTGRES_DB: task_manager_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432

volumes:
  db_data: